version: '3.8'
services:
  db:
    image: mysql:5.7.31
    environment:
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./tmp/config:/etc/mysql/conf.d

volumes:
    dbdata:
        driver: local